// Generated by CoffeeScript 1.9.3
(function() {
  var GoogleSpreadsheet, _, _fetchSpreadsheet, _getSheetInfo, async;

  _ = require("lodash");

  async = require("async");

  GoogleSpreadsheet = require("google-spreadsheet");

  _getSheetInfo = function(sheetId, creds, callback) {
    var sheet;
    sheet = new GoogleSpreadsheet(sheetId);
    if (creds) {
      return async.waterfall([
        function(cb) {
          return sheet.useServiceAccountAuth(creds, cb);
        }, function(cb) {
          return sheet.getInfo(cb);
        }
      ], callback);
    } else {
      return sheet.getInfo(callback);
    }
  };

  _fetchSpreadsheet = function(sheetInfo, title, transform, callback) {
    var sheets;
    sheets = _.filter(sheetInfo.worksheets, {
      title: title
    });
    return async.map(sheets, function(sheet, cb) {
      return sheet.getRows(cb);
    }, function(err, datas) {
      datas = _.map(datas, transform);
      if (sheets.length === 1) {
        return datas[0];
      } else {
        return datas;
      }
    });
  };

  module.exports = function(arg) {
    var callback, creds, opts, sheetId;
    sheetId = arg.sheetId, creds = arg.creds, opts = arg.opts, callback = arg.callback;
    opts = _.flatten([opts], true);
    return async.waterfall([
      function(cb) {
        return _getSheetInfo(sheetId, creds, cb);
      }, function(sheetInfo, cb) {
        return async.map(_.map(opts), function(opt, cb) {
          return _fetchSpreadsheet(sheetInfo, opt.title, opt.transform, cb);
        }, cb);
      }
    ], callback);
  };

}).call(this);
